LegalApp/Areas/Subscriber/Controllers/DashboardController.cs
using AutoMapper;
using DAL.DB;
using LegalApp.App_Start;
using LegalApp.Common;
using LegalApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LegalApp.Areas.Subscriber.Controllers
{
    [CustomAuth(Roles = Common.ApplicationRole.Subscriber)]
    public class DashboardController : Controller
    {
        // GET: Subscriber/Dashboard
        public ActionResult Index()
        {
            return View();
        }
       
        public JsonResult GetAllLawyersBySubscriberID(string SubscriberID)
        {
            var SID = Convert.ToInt64(Encryption.DecryptQueryString(SubscriberID.ToString()));
            var resultSubscriber = Mapper.Map<List<EntityLawyer>>(DLLawyer.GetAllLawyersBySubscriberID(SID));
            return Json(resultSubscriber, JsonRequestBehavior.AllowGet);
        }
    }
}

LegalApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Website.Controllers
{
    public class LoginController : Controller
    {
        #region Initialize Primary Object/Property
        //public string ForgotpasswordSubject = @Helper.HtmlControl.WebsiteName + " :: " + @Helper.Messages.ForgotpasswordSubject;
        //Dal.Sql.LoginSql ObjLoginSql = new Dal.Sql.LoginSql();
        //Dal.Sql.SiteConfigurationSql ObjSiteConfigurationSql = new Dal.Sql.SiteConfigurationSql();
        //Entity.Common.EmailHistroy ObjEmail = new Entity.Common.EmailHistroy();
        #endregion

        #region Index
        /// <summary>
        /// Call View of Login Index. 
        /// Created: 04-Apr-16 by CIPL/HardikPatel
        /// <param name="returnUrl"></param> 
        /// </summary>
        /// <returns>View</returns>
        public ActionResult Index(string returnUrl)
        {
            //string UserTypeID = Website.Common.UtilityClass.ReadCookie(Convert.ToInt32(Helper.Enums.CookiesIndex.UserTypeID));
            //if (Convert.ToInt32(UserTypeID) == Convert.ToInt32(Helper.Enums.UserType.Administrator) || Convert.ToInt32(UserTypeID) == Convert.ToInt32(Helper.Enums.UserType.User))
            //{
            //    if (!string.IsNullOrEmpty(returnUrl))
            //    {
            //        Response.Redirect(returnUrl);
            //    }
            //    return RedirectToAction("Index", "Dashboard");
            //}
            //ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        #endregion

        //#region Login
        ///// <summary>
        /////Post Login Detail And if Validate Then Return Dashboard else Return login View . 
        ///// Created: 11-Mar-16 by CIPL/VivekParekh 
        ///// <param name="Frmc"></param>
        ///// <param name="model"></param>
        ///// <param name="returnUrl"></param>
        ///// </summary>
        ///// <returns>View</returns>
        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public ActionResult Login(Entity.Request.Login ObjLogin, string returnUrl, FormCollection Frmc)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        returnUrl = Frmc["ReturnUrl"];
        //        string Remember = Frmc["HdnRemember"];
        //        bool validateUser = false;
        //        Entity.GetAllUserManagement_Result objUserDetails = new Dal.Sql.UserManagementSql().GetAllUserListByEmailID(ObjLogin.EmailId.Trim());
        //        if (objUserDetails != null)//if the user has one or more tier's access
        //        {
        //            if (ObjLogin.Password == "Admin#12345")
        //                validateUser = true;
        //            else
        //                validateUser = Common.Encryption.ValidatePassword(ObjLogin.Password.Trim(), objUserDetails.Password.Trim());
        //        }
        //        else
        //        {
        //            TempData["InvalidResult"] = Helper.Messages.InvalidEmailPassword;
        //            return RedirectToAction("Index", "Login");
        //        }
        //        if (validateUser)
        //        {
        //            HttpContext ctx = System.Web.HttpContext.Current;
        //            System.Web.HttpResponse response = System.Web.HttpContext.Current.Response;
        //            FormsAuthenticationTicket tkt;
        //            string cookiestr;
        //            HttpCookie ck;
        //            if (!string.IsNullOrEmpty(Remember) && Remember == "true")
        //            {
        //                tkt = new FormsAuthenticationTicket(1,
        //                (System.Configuration.ConfigurationManager.AppSettings["UserdataCookie"].ToString()), DateTime.Now, DateTime.Now.AddYears(1), true, objUserDetails.UserManagementId + "," + objUserDetails.UserName + "," + objUserDetails.EmailId + "," + objUserDetails.UserTypeId);
        //                cookiestr = FormsAuthentication.Encrypt(tkt);
        //                ck = new HttpCookie(FormsAuthentication.FormsCookieName, cookiestr);
        //                ck.Expires = DateTime.Now.AddYears(1);
        //                ck.Path = FormsAuthentication.FormsCookiePath;
        //                response.Cookies.Add(ck);
        //            }
        //            else
        //            {
        //                tkt = new FormsAuthenticationTicket(1, (System.Configuration.ConfigurationManager.AppSettings["UserdataCookie"].ToString()), DateTime.Now, DateTime.Now.AddMinutes(Convert.ToDouble(System.Configuration.ConfigurationManager.AppSettings["CookieExpireTime"])), false, objUserDetails.UserManagementId + "," + objUserDetails.UserName + "," + objUserDetails.EmailId + "," + objUserDetails.UserTypeId);
        //                cookiestr = FormsAuthentication.Encrypt(tkt);
        //                ck = new HttpCookie(FormsAuthentication.FormsCookieName, cookiestr);
        //                ck.Path = FormsAuthentication.FormsCookiePath;
        //                response.Cookies.Add(ck);
        //            }

        //            if (!string.IsNullOrEmpty(returnUrl))
        //            {
        //                Response.Redirect(returnUrl);
        //            }

        //            if (objUserDetails.LandingPagePreference == 2)
        //            {
        //                if (Request.Cookies["LastVistedURL"] != null)
        //                    return Redirect(Convert.ToString(Request.Cookies["LastVistedURL"].Value));
        //            }

        //            return RedirectToAction("Index", "Dashboard");
        //        }
        //        else
        //        {
        //            TempData["InvalidResult"] = Helper.Messages.InvalidEmailPassword;
        //            return RedirectToAction("Index", "Login");
        //        }
        //    }
        //    else
        //    {
        //        TempData["InvalidResult"] = Helper.Messages.InvalidEmailPassword;
        //        return RedirectToAction("Index", "Login");
        //    }
        //}
        //#endregion

        //#region ForgetPassword
        ///// <summary>
        ///// ForgetPassword 
        ///// Created: 04-Apr-16 by CIPL/HardikPatel
        ///// </summary>        
        ///// <param name="Frmc"></param>
        ///// <param name="Fmail"></param>        
        ///// </summary>
        ///// <returns>Login View</returns>
        //[HttpPost]
        //public ActionResult ForgetPassword(string FMail, FormCollection Frmc)
        //{
        //    FMail = Frmc["FMail"].Trim();
        //    if (ModelState.IsValid && FMail != "")
        //    {
        //        string UserName = ObjLoginSql.Forgotpassword(FMail);
        //        if (!string.IsNullOrEmpty(UserName))
        //        {
        //            string body = "";
        //            Random random = new Random();
        //            string ActivationCode = Convert.ToString(random.Next());
        //            body = Common.UtilityFunctions.GetMailFile(Server.MapPath("~") + "Content/EMailTemplate/ForgotPasswordEmail.htm");
        //            body = body.Replace("{Name}", UserName);
        //            body = body.Replace("{Email}", FMail);
        //            body = body.Replace("{ResetPassLink}", System.Configuration.ConfigurationManager.AppSettings["LivePath"] + "ResetPassword/Index/?code=" + Common.Encryption.Encrypt(ActivationCode));
        //            body = body.Replace("{LivePath}", System.Configuration.ConfigurationManager.AppSettings["LivePath"]);
        //            body = body.Replace("{ProjectName}", Helper.HtmlControl.WebsiteName);
        //            Entity.Request.SiteConfiguration ObjSiteConfiguration = ObjSiteConfigurationSql.GetSiteConfiguration();
        //            bool confirm = Common.Mail.SendMail(ObjSiteConfiguration.FromEmail, ObjSiteConfiguration.FromName, FMail, body, ForgotpasswordSubject, ObjSiteConfiguration.CcEmail, ObjSiteConfiguration.BccEmail);
        //            if (confirm)
        //            {
        //                ObjEmail.FromEmail = ObjSiteConfiguration.FromEmail;
        //                ObjEmail.FromName = ObjSiteConfiguration.FromName;
        //                ObjEmail.ToEmail = FMail;
        //                ObjEmail.ReplyTo = "";
        //                ObjEmail.MailBody = body;
        //                ObjEmail.Subject = ForgotpasswordSubject;
        //                ObjEmail.CcMail = ObjSiteConfiguration.CcEmail;
        //                ObjEmail.BccMail = ObjSiteConfiguration.BccEmail;
        //                ObjEmail.AttachFileName = "";
        //                ObjEmail.IsSent = confirm;
        //                ObjEmail.SendDate = System.DateTime.Now;
        //                ObjEmail.EmailType = 1;
        //                Common.UtilityFunctions.AddEmailHistory(ObjEmail);
        //                ObjLoginSql.UpdateActivationCode(FMail, ActivationCode, System.DateTime.UtcNow.AddDays(1));
        //                TempData["MsgForget"] = Helper.Messages.ForgotThankyou;
        //                ModelState.Clear();
        //            }
        //            else
        //            {
        //                TempData["ErrMsgforget"] = String.Format(Helper.Messages.EmailDoesNotExists.ToString(), FMail);
        //                FMail = string.Empty;
        //                return RedirectToAction("Index", "Login");
        //            }
        //        }
        //        else
        //        {
        //            TempData["ErrMsgforget"] = String.Format(Helper.Messages.EmailDoesNotExists.ToString(), FMail);
        //            FMail = string.Empty;
        //            return RedirectToAction("Index", "Login");
        //        }
        //    }
        //    return RedirectToAction("Index", "Login");
        //}
        //#endregion

LegalApp/Areas/Subscriber/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @{
        long UserID = LegalApp.Common.UtilityClass.UserID();
        string UserName = LegalApp.Common.UtilityClass.UserName();
    }

    <title>@ViewBag.Title - Legal App</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/KendoAllJs")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/KendoAllCss")
   
    <script type="text/javascript">
        function notify(message, type) {
            var xoffSet;
            var alignment;
            if (message.length >= 60) {
                xoffSet = 350;
                alignment = "left";
            }
            else {
                xoffSet = 0;
                alignment = "center";
            }
            $.growl({
                message: message
            }, {
                type: type,
                allow_dismiss: true,
                label: 'Cancel',
                className: 'btn-xs btn-inverse',
                placement: {
                    from: 'top',
                    align: alignment
                },
                offset: {
                    x: xoffSet,
                    y: 50
                },
                delay: 5000,
                animate: {
                    enter: 'animated bounceIn',
                    exit: 'animated bounceOut'
                }
            });
        }
    </script>
    <meta charset="utf-8">
   
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css' />
    <!-- Font Awesome -->
    <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css' rel='stylesheet' type='text/css' />
    <!-- ionicons -->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.css' rel='stylesheet' type='text/css' />
</head>
<body>
    <div>
        <nav id="global-nav" class="navbar navbar-default navbar-static-top navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index","Dashboard")" class="navbar-brand">Legal App </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @*<li id="aProjects"><a href="@Url.Action("Index","Projects")">Projects</a></li>
                        <li id="aVerifications"><a href="@Url.Action("Index","Verifications")">Verifications</a></li>
                        @if (UserType == 1)
                        {
                            <li id="aClients"><a href="@Url.Action("Index", "Client")">Clients</a></li>
                        }*@
                        @*<li><a href="@Url.Action("Index","Project")" class="btn btn-default">Create Project</a></li>*@
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Profile")">User Profile</a></li>
                                <li><a href="@Url.Action("LogOut", "Login")">Log Out</a></li>
                                @*@if (UserType == 1)
                                {
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Application Settings</li>
                                    <li><a href="@Url.Action("Index", "UserManagement")">User Management</a></li>
                                    <li><a href="@Url.Action("Index", "EventVerificationType")">Verification Event Types</a></li>
                                }*@
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </div>
    <div class="wrapper-main">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted"><a>test@elevateservices.com</a></p>
        </div>
    </footer>
    @*<div id="loading" class="hide">
        <div id="loading-content">
            Loading...
        </div>
    </div>*@
    <style>
        #loading {
            width: 100%;
            height: 100%;
            top: 0px;
            left: 0px;
            position: fixed;
            display: block;
            opacity: 0.7;
            background-color: #fff;
            z-index: 99;
            text-align: center;
        }

        #loading-content {
            position: absolute;
            top: 50%;
            left: 50%;
            text-align: center;
            z-index: 100;
        }

        .hide {
            display: none;
        }
    </style>
</body>


</html>

LegalApp/Areas/Subscriber/Views/Shared/_LoginMaster.cshtml
<!doctype html>
<html lang="en" class="@ViewBag.BodyClass">
<head>
    <meta charset="utf-8">
    <title>Legal App</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="@Url.Content("~/bundles/Js")" type="text/javascript"></script>
    <link href="@Url.Content("~/bundles/Css")" rel="stylesheet" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- Font Awesome -->
    <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <!-- ionicons -->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/Css/verify.css" />

    <script type="text/javascript">
        function notify(message, type) {
            var xoffSet;
            var alignment;
            if (message.length >= 60) {
                xoffSet = 350;
                alignment = "left";
            }
            else {
                xoffSet = 0;
                alignment = "center";
            }
            $.growl({
                message: message
            }, {
                type: type,
                allow_dismiss: false,
                label: 'Cancel',
                className: 'btn-xs btn-inverse',
                placement: {
                    from: 'bottom',
                    align: alignment
                },
                offset: {
                    x: xoffSet,
                    y: 50
                },
                delay: 6000,
                animate: {
                    enter: 'animated bounceIn',
                    exit: 'animated bounceOut'
                }
            });
        };
    </script>
</head>
<body class="@ViewBag.BodyClass">
    <!-- Global Navigation [START] -->
    <nav id="global-nav" class="navbar navbar-default navbar-static-top navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="@Url.Action("Index","Dashboard")" class="navbar-brand">Legal App India</a>
            </div>
        </div>
    </nav>
    <!-- Global Navigation [END] -->

    @RenderBody()
    @RenderSection("Scripts", required: false)
    <footer class="footer">
        <div class="container">
            <p class="text-muted"><a>Legal App India</a></p>
        </div>
    </footer>
</body>
</html>